### ISSUE TITLE
deoplete-jedi fails to load on vim + pynvim 0.4.0

### ISSUE THREAD

**Issue by z0rc** [deoplete-plugins/deoplete-jedi#237]
# Problem summary
```
[deoplete] Traceback (most recent call last):
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete.nvim/rplugin/python3/deoplete/child.py", line 448, in _itersource
    source.on_init(context)
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 74, in on_init
    'deoplete#sources#jedi#statement_length', 0)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#jedi#statement_length'
Error when loading source jedi: 'deoplete#sources#jedi#statement_length'. Ignoring..  Use :messages / see above for error details.
```

## Expected
deoplete-jedi loads successfully.

## Environment Information

 * OS: macOS 10.14.6
 * Vim version: 8.1.2350

## Provide a minimal init.vim with less than 50 lines (required)

```vim
set nocompatible
set runtimepath+=$HOME/vim-deoplete-jedi-test/vim-hug-neovim-rpc/
set runtimepath+=$HOME/vim-deoplete-jedi-test/nvim-yarp/
set runtimepath+=$HOME/vim-deoplete-jedi-test/deoplete.nvim/
set runtimepath+=$HOME/vim-deoplete-jedi-test/deoplete-jedi/

let g:deoplete#enable_at_startup=1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"

filetype plugin indent on
```

## Steps to reproduce the issue after starting Vim (required)

 1. `echo 'import multiprocessing' > test.py`
 1. `vim -u minimal.vim`
 1. `:e test.py`
 1. `:messages`

## Upload the logfile(s)
vim_log_py3_neovim_rpc_server with pynvim 0.4.0 - fails to load deoplete-jedi
https://paste.ubuntu.com/p/DTKGtQPx6n/

vim_log_py3_neovim_rpc_server with pynvim 0.3.2 - deoplete-jedi loads successfully and completion works
https://paste.ubuntu.com/p/4CBCZd5rxz/

**Comment by z0rc** [comment]
Might be related to https://github.com/neovim/pynvim/pull/405

**Comment by Shougo** [comment]
Please test #238.

**Comment by z0rc** [comment]
@Shougo this seems fixed loading of jedi source, but completion still doesn't work. There is new error in `:messages` that occurs when jedi is asked for candidates.
```
[deoplete] Traceback (most recent call last):
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete.nvim/rplugin/python3/deoplete/child.py", line 189, in _gather_results
    result = self._get_result(context, source)
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete.nvim/rplugin/python3/deoplete/child.py", line 249, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/Ihor_Urazov/vim-deoplete-test/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 150, in gather_candidates
    'deoplete#sources#jedi#python_path', None)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/Ihor_Urazov/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#jedi#python_path'
Error from jedi: 'deoplete#sources#jedi#python_path'.  Use :messages / see above for error details.
...
[deoplete] Too many errors from "jedi". This source is disabled until Neovim is restarted.
```

**Comment by Shougo** [comment]
I have fixed the error.  Please test the branch again.

**Comment by z0rc** [comment]
I confirm that last update in PR fixed the issue. jedi source loads successfully and completion works as expected.

**Comment by Shougo** [comment]
Thank you for the test.
