### ISSUE TITLE
Error from jedi: __init__() got an unexpected keyword argument 'code'

### ISSUE THREAD

**Issue by eInyzant** [deoplete-plugins/deoplete-jedi#270]
# Problems summary
When I start typing anything I got pleinty of errors, after what the plugin says it is disabled until restart.

## Expected
When I start typing, I should see the popup for completion

## Environment Information

 * deoplete version (SHA1): git commit 2849fa544b9a3a07ec1ddafb2bb6f72945b24c62

 * OS: Linux Ubuntu 20.04

 * neovim/Vim `:version` output:
``` :version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-
security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -ped
antic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fsta
ck-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HA
S_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1
 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compilé par team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info
```
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log{PID}
    - and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: keybackspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
     - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.19.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
call plug#begin('~/.vim/plugged')
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'deoplete-plugins/deoplete-jedi'
call plug#end()

filetype plugin indent on     " required!

" General {
	set fileencoding=utf-8 " Encodage des caractères pour les fichiers
	set enc=utf-8       " Encodage utilisé par vim (conversion effectué si différent de fileencoding)
	set tenc=utf-8  " Encodage utilisé par vim (conversion effectué si différent de fileencoding)
	syntax on                   " syntax highlighting
	set mouse=a                 " automatically enable mouse usage
	set fileformat=unix

" Key Mappings {

	" Yank from the cursor to the end of the line, to be consistent with C and D.
	nnoremap Y y$
	let mapleader=","

" }

" Plugins {

  " Deoplete {
    let g:deoplete#enable_at_startup = 1
  "}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Open a python file
 2. Start typing anything in insertion mode
 3. => errors

## Upload the log file
```
[deoplete] Traceback (most recent call last):                                                                                  
  File "/home/erwan/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/erwan/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 199, in gather_candidates
    script = self.get_script(source, filename, environment=self._env)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 144, in get_script
    return self._jedi.Script(code=source, path=filename, environment=self._env)
TypeError: __init__() got an unexpected keyword argument 'code'
Error from jedi: __init__() got an unexpected keyword argument 'code'.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/home/erwan/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 194, in _gather_results
    result = self._get_result(context, source)
  File "/home/erwan/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 254, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 199, in gather_candidates
    script = self.get_script(source, filename, environment=self._env)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/home/erwan/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 144, in get_script
    return self._jedi.Script(code=source, path=filename, environment=self._env)
TypeError: __init__() got an unexpected keyword argument 'code'
Error from jedi: __init__() got an unexpected keyword argument 'code'.  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
I don't reproduce your error.

The code argument is exists. So your jedi is very old.
https://github.com/davidhalter/jedi/blob/master/jedi/api/__init__.py#L108

What is your jedi's version??

**Comment by Shougo** [comment]
You should execute `pip3 install --upgrade jedi` in command line.

**Comment by eInyzant** [comment]
@Shougo Thank you you were right. In fact I think jedi was installed a long time ago on my computer and when I ran this command ``` pip3 install --user jedi ``` from the README, it probably did nothing, just telling me that jedi is already installed.
Maybe you could add a notice on your README.

Thank you again for your time :)

**Comment by Shougo** [comment]
OK.  I have updated it.
